repos:
-   repo: https://github.com/ambv/black
    rev: 21.7b0
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://github.com/pycqa/flake8
    rev: 3.9.0
    hooks:
    - id: flake8
-   repo: local
    hooks:
    -   id: pytest
        name: run tests
        entry: pytest tests -vv
        language: system
        always_run: true
        pass_filenames: false
