[tool.black]
line-length = 80
target-version = ["py38"]

[tool.coverage.run]
omit = ["tests/*"]

[tool.coverage.report]
omit = ["tests/*", ]
exclude_lines = ["def name"]

[tool.pytest.ini_options]
addopts = "-vv --cov ./ --cov-report term-missing"
