name: dagfinn_actions
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - black==21.7b0 # Dependency issue: https://github.com/psf/black/issues/2520
  - flake8
  - pre-commit
  - pytest
  - pytest-cov
  - pip
  - bs4
  - opencv
  - pip:
    - pip
    - rasa[spacy]==3.0.9
    - pyowm
    - selenium
    - webdriver-manager
    - pycountry
    - pandas
    - fuzzywuzzy
    - zmq
    - countryinfo
    - face_recognition
    - Levenshtein
    - pyzbar
    - folium
    