name: build

on: 
  pull_request:
    paths:
      - 'actions/**'
      - 'addons/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8' 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pre-commit flake8
    - name: Check black formatting
      run: |
        pre-commit black
    - name: Run tests
      run: |
        pytest tests --cov=./ --cov-report=xml
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
